FROM node:8.2.1

RUN mkdir -p /usr/src/app/dist

WORKDIR /usr/src/app

COPY ./src ./src
COPY ./config ./config
COPY ./package.json ./package-lock.json ./
COPY ./tsconfig* ./
COPY webpack.config.js ./

RUN npm install
RUN npm run build

EXPOSE 8585

CMD ["npm", "start"]