FROM node:7.10

RUN mkdir -p /usr/src/app/dist

WORKDIR /usr/src/app

COPY ./dist ./dist
COPY ./package.json ./package-lock.json ./

RUN npm install

RUN ls -la /usr/src/app/*

EXPOSE 8585

CMD ["node", "./dist/server.js"]